#!/usr/bin/env python3
"""
Convert BBC Micro Chuckie Egg scenes.basm to Game Boy 20x18 tile maps.

BBC grid: 20 cols x ~25 rows (rows 1-23 used, implied floor at 24)
GB grid:  20 cols x 18 rows (rows 0-17; 0=ceiling, 17=floor)

Scaling: gb_row = round(bbc_row * 17 / 24)
Columns map 1:1 (both 0-19).
"""

import re
import sys
import os

BBC_MAX_ROW = 24
GB_COLS     = 20
GB_ROWS     = 18

TILE_EMPTY           = 0
TILE_PLATFORM        = 1
TILE_LADDER          = 2
TILE_EGG             = 3
TILE_GRAIN           = 4
TILE_SOLID           = 5
TILE_LADDER_PLATFORM = 6


def bbc_to_gb_row(r):
    # BBC row 1 = floor (bottom), rows increase going UP toward ceiling
    # GB row 0 = ceiling (top), GB row 17 = floor (bottom)
    # Invert: BBC 1 → GB 17, BBC 24 → GB 0
    return round((BBC_MAX_ROW - r) * 17 / (BBC_MAX_ROW - 1))


def parse_equb_nums(line):
    """Return list of ints if line is 'EQUB n, n, ...' with only plain integers."""
    line = line.strip()
    if not line.startswith('EQUB'):
        return None
    args = line[4:].strip()
    tokens = [t.strip() for t in args.split(',')]
    try:
        return [int(t) for t in tokens]
    except ValueError:
        return None  # expression or symbol present — skip


def parse_scenes(path):
    scenarios = []
    current   = None
    section   = None

    with open(path) as f:
        for line in f:
            line = line.strip()
            if re.match(r'\.scenario_\d+', line):
                if current is not None:
                    scenarios.append(current)
                current = {s: [] for s in ('walls', 'ladders', 'eggs', 'grain', 'chickens')}
                section = None
            elif line in ('.walls', '.ladders', '.lift', '.eggs', '.grain', '.chickens'):
                section = line[1:]  # strip leading dot
            elif line.startswith('EQUB') and section and section != 'lift' and current is not None:
                nums = parse_equb_nums(line)
                if nums:
                    current[section].append(nums)

    if current is not None:
        scenarios.append(current)

    return scenarios


def build_map(scenario):
    level = [[TILE_EMPTY] * GB_COLS for _ in range(GB_ROWS)]

    # Floor only — ceiling row left empty
    for c in range(GB_COLS):
        level[17][c] = TILE_PLATFORM

    # Walls → platforms
    for entry in scenario['walls']:
        if len(entry) != 3:
            continue
        bbc_row, cs, ce = entry
        gr = bbc_to_gb_row(bbc_row)
        if 0 < gr < 17:
            for c in range(cs, min(ce + 1, GB_COLS)):
                level[gr][c] = TILE_PLATFORM

    # Ladders
    for entry in scenario['ladders']:
        if len(entry) != 3:
            continue
        col, bbc_rs, bbc_re = entry
        if not (0 <= col < GB_COLS):
            continue
        # After Y-inversion, higher BBC rows → lower GB rows, so swap if needed
        gr_top = min(bbc_to_gb_row(bbc_rs), bbc_to_gb_row(bbc_re))
        gr_bot = max(bbc_to_gb_row(bbc_rs), bbc_to_gb_row(bbc_re))
        for r in range(max(1, gr_top), min(17, gr_bot + 1)):
            if level[r][col] == TILE_EMPTY:
                level[r][col] = TILE_LADDER
            elif level[r][col] == TILE_PLATFORM:
                level[r][col] = TILE_LADDER_PLATFORM

    # Eggs
    for entry in scenario['eggs']:
        if len(entry) != 2:
            continue
        col, bbc_row = entry
        gr = bbc_to_gb_row(bbc_row)
        if 0 < gr < 17 and 0 <= col < GB_COLS:
            if level[gr][col] in (TILE_EMPTY, TILE_LADDER):
                level[gr][col] = TILE_EGG

    # Grain
    for entry in scenario['grain']:
        if len(entry) != 2:
            continue
        col, bbc_row = entry
        gr = bbc_to_gb_row(bbc_row)
        if 0 < gr < 17 and 0 <= col < GB_COLS:
            if level[gr][col] == TILE_EMPTY:
                level[gr][col] = TILE_GRAIN

    return level


def main():
    script_dir  = os.path.dirname(os.path.abspath(__file__))
    scenes_path = os.path.join(script_dir, '..', 'scenes.basm')
    scenarios   = parse_scenes(scenes_path)

    print('/* Auto-generated by tools/convert_levels.py — do not edit */')
    print('#ifndef LEVEL_DATA_H')
    print('#define LEVEL_DATA_H')
    print()
    print('#include <stdint.h>')
    print()
    print('#define TILE_EMPTY           0')
    print('#define TILE_PLATFORM        1')
    print('#define TILE_LADDER          2')
    print('#define TILE_EGG             3')
    print('#define TILE_GRAIN           4')
    print('#define TILE_SOLID           5')
    print('#define TILE_LADDER_PLATFORM 6')
    print()
    print(f'#define LEVEL_COLS {GB_COLS}U')
    print(f'#define LEVEL_ROWS {GB_ROWS}U')
    print(f'#define NUM_LEVELS {len(scenarios)}U')
    print()

    for i, sc in enumerate(scenarios):
        lvl = build_map(sc)
        print(f'static const uint8_t level{i}[{GB_ROWS}][{GB_COLS}] = {{')
        for row in lvl:
            print('    {' + ','.join(str(t) for t in row) + '},')
        print('};')
        print()

    print(f'static const uint8_t* const levels[{len(scenarios)}] = {{')
    for i in range(len(scenarios)):
        print(f'    (const uint8_t*)level{i},')
    print('};')
    print()
    print('#endif /* LEVEL_DATA_H */')


if __name__ == '__main__':
    main()
